package com.yc.SellStore.bean;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ID
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.clientID
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private Integer clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ID
     *
     * @return the value of address.ID
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ID
     *
     * @param id the value for address.ID
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.clientID
     *
     * @return the value of address.clientID
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.clientID
     *
     * @param clientid the value for address.clientID
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }
}