package com.yc.SellStore.bean;

public class Admininfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.admin_id
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.admin_name
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.admin_pwd
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private String adminPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.tel
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.sex
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.admin_id
     *
     * @return the value of admininfo.admin_id
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.admin_id
     *
     * @param adminId the value for admininfo.admin_id
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.admin_name
     *
     * @return the value of admininfo.admin_name
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.admin_name
     *
     * @param adminName the value for admininfo.admin_name
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.admin_pwd
     *
     * @return the value of admininfo.admin_pwd
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public String getAdminPwd() {
        return adminPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.admin_pwd
     *
     * @param adminPwd the value for admininfo.admin_pwd
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setAdminPwd(String adminPwd) {
        this.adminPwd = adminPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.tel
     *
     * @return the value of admininfo.tel
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.tel
     *
     * @param tel the value for admininfo.tel
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.sex
     *
     * @return the value of admininfo.sex
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.sex
     *
     * @param sex the value for admininfo.sex
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }
}