package com.yc.SellStore.bean;

import java.util.Date;

public class Collect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.id
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.clientid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.goodsid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.ordertime
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Date ordertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.id
     *
     * @return the value of collect.id
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.id
     *
     * @param id the value for collect.id
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.clientid
     *
     * @return the value of collect.clientid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.clientid
     *
     * @param clientid the value for collect.clientid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.goodsid
     *
     * @return the value of collect.goodsid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.goodsid
     *
     * @param goodsid the value for collect.goodsid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.ordertime
     *
     * @return the value of collect.ordertime
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.ordertime
     *
     * @param ordertime the value for collect.ordertime
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }
}