package com.yc.SellStore.bean;

public class Driver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Driver.id
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Driver.truename
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private String truename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Driver.idcardnum
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private String idcardnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Driver.pwd
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Driver.phone
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Driver.id
     *
     * @return the value of Driver.id
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Driver.id
     *
     * @param id the value for Driver.id
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Driver.truename
     *
     * @return the value of Driver.truename
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Driver.truename
     *
     * @param truename the value for Driver.truename
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Driver.idcardnum
     *
     * @return the value of Driver.idcardnum
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public String getIdcardnum() {
        return idcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Driver.idcardnum
     *
     * @param idcardnum the value for Driver.idcardnum
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setIdcardnum(String idcardnum) {
        this.idcardnum = idcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Driver.pwd
     *
     * @return the value of Driver.pwd
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Driver.pwd
     *
     * @param pwd the value for Driver.pwd
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Driver.phone
     *
     * @return the value of Driver.phone
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Driver.phone
     *
     * @param phone the value for Driver.phone
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}