package com.yc.SellStore.bean;

public class Driver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.id
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.truename
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private String truename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.idcardnum
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private String idcardnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.pwd
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.phone
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.id
     *
     * @return the value of driver.id
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.id
     *
     * @param id the value for driver.id
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.truename
     *
     * @return the value of driver.truename
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.truename
     *
     * @param truename the value for driver.truename
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.idcardnum
     *
     * @return the value of driver.idcardnum
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public String getIdcardnum() {
        return idcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.idcardnum
     *
     * @param idcardnum the value for driver.idcardnum
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setIdcardnum(String idcardnum) {
        this.idcardnum = idcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.pwd
     *
     * @return the value of driver.pwd
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.pwd
     *
     * @param pwd the value for driver.pwd
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.phone
     *
     * @return the value of driver.phone
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.phone
     *
     * @param phone the value for driver.phone
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}