package com.yc.SellStore.bean;

public class Evalute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evalute.id
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evalute.clientid
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    private String clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evalute.driverid
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    private String driverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evalute.content
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evalute.evalutecol
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    private String evalutecol;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evalute.id
     *
     * @return the value of evalute.id
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evalute.id
     *
     * @param id the value for evalute.id
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evalute.clientid
     *
     * @return the value of evalute.clientid
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evalute.clientid
     *
     * @param clientid the value for evalute.clientid
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    public void setClientid(String clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evalute.driverid
     *
     * @return the value of evalute.driverid
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    public String getDriverid() {
        return driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evalute.driverid
     *
     * @param driverid the value for evalute.driverid
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    public void setDriverid(String driverid) {
        this.driverid = driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evalute.content
     *
     * @return the value of evalute.content
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evalute.content
     *
     * @param content the value for evalute.content
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evalute.evalutecol
     *
     * @return the value of evalute.evalutecol
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    public String getEvalutecol() {
        return evalutecol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evalute.evalutecol
     *
     * @param evalutecol the value for evalute.evalutecol
     *
     * @mbg.generated Tue May 14 21:04:47 CST 2019
     */
    public void setEvalutecol(String evalutecol) {
        this.evalutecol = evalutecol;
    }
}