package com.yc.SellStore.bean;

public class Olderlist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column olderList.id
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column olderList.clientid
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    private Integer clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column olderList.goodsid
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    private Integer goodsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column olderList.id
     *
     * @return the value of olderList.id
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column olderList.id
     *
     * @param id the value for olderList.id
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column olderList.clientid
     *
     * @return the value of olderList.clientid
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column olderList.clientid
     *
     * @param clientid the value for olderList.clientid
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column olderList.goodsid
     *
     * @return the value of olderList.goodsid
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column olderList.goodsid
     *
     * @param goodsid the value for olderList.goodsid
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }
}