
package com.yc.SellStore.bean;

public class Olderlist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column olderlist.id
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column olderlist.clientid
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private Integer clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column olderlist.goodsid
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    private Integer goodsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column olderlist.id
     *
     * @return the value of olderlist.id
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column olderlist.id
     *
     * @param id the value for olderlist.id
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column olderlist.clientid
     *
     * @return the value of olderlist.clientid
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column olderlist.clientid
     *
     * @param clientid the value for olderlist.clientid
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column olderlist.goodsid
     *
     * @return the value of olderlist.goodsid
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column olderlist.goodsid
     *
     * @param goodsid the value for olderlist.goodsid
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }
}