package com.yc.SellStore.bean;

import java.util.Date;

public class Orderlist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.id
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.orderId
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.clientid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.goodsid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.count
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.status
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.ordertime
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Date ordertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.id
     *
     * @return the value of orderList.id
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.id
     *
     * @param id the value for orderList.id
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.orderId
     *
     * @return the value of orderList.orderId
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.orderId
     *
     * @param orderid the value for orderList.orderId
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.clientid
     *
     * @return the value of orderList.clientid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.clientid
     *
     * @param clientid the value for orderList.clientid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.goodsid
     *
     * @return the value of orderList.goodsid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.goodsid
     *
     * @param goodsid the value for orderList.goodsid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.count
     *
     * @return the value of orderList.count
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.count
     *
     * @param count the value for orderList.count
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.status
     *
     * @return the value of orderList.status
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.status
     *
     * @param status the value for orderList.status
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.ordertime
     *
     * @return the value of orderList.ordertime
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.ordertime
     *
     * @param ordertime the value for orderList.ordertime
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }
}