package com.yc.SellStore.bean;

public class Peisong {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peisong.id
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peisong.clientid
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    private Integer clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peisong.clientname
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    private String clientname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peisong.phone
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peisong.addres
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    private String addres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peisong.ps_name
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    private String psName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peisong.ps_tel
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    private String psTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peisong.id
     *
     * @return the value of peisong.id
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peisong.id
     *
     * @param id the value for peisong.id
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peisong.clientid
     *
     * @return the value of peisong.clientid
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peisong.clientid
     *
     * @param clientid the value for peisong.clientid
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peisong.clientname
     *
     * @return the value of peisong.clientname
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peisong.clientname
     *
     * @param clientname the value for peisong.clientname
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public void setClientname(String clientname) {
        this.clientname = clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peisong.phone
     *
     * @return the value of peisong.phone
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peisong.phone
     *
     * @param phone the value for peisong.phone
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peisong.addres
     *
     * @return the value of peisong.addres
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public String getAddres() {
        return addres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peisong.addres
     *
     * @param addres the value for peisong.addres
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public void setAddres(String addres) {
        this.addres = addres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peisong.ps_name
     *
     * @return the value of peisong.ps_name
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public String getPsName() {
        return psName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peisong.ps_name
     *
     * @param psName the value for peisong.ps_name
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public void setPsName(String psName) {
        this.psName = psName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peisong.ps_tel
     *
     * @return the value of peisong.ps_tel
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public String getPsTel() {
        return psTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peisong.ps_tel
     *
     * @param psTel the value for peisong.ps_tel
     *
     * @mbg.generated Tue May 14 21:18:04 CST 2019
     */
    public void setPsTel(String psTel) {
        this.psTel = psTel;
    }
}