package com.yc.SellStore.bean;

public class Picture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.id
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.goodsid
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.picture
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.id
     *
     * @return the value of picture.id
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.id
     *
     * @param id the value for picture.id
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.goodsid
     *
     * @return the value of picture.goodsid
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.goodsid
     *
     * @param goodsid the value for picture.goodsid
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.picture
     *
     * @return the value of picture.picture
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.picture
     *
     * @param picture the value for picture.picture
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }
}