package com.yc.SellStore.bean;

import java.util.Date;

public class Shopcar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.id
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.clientid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.goodsid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.count
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.status
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.ordertime
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    private Date ordertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.id
     *
     * @return the value of shopcar.id
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.id
     *
     * @param id the value for shopcar.id
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.clientid
     *
     * @return the value of shopcar.clientid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.clientid
     *
     * @param clientid the value for shopcar.clientid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.goodsid
     *
     * @return the value of shopcar.goodsid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.goodsid
     *
     * @param goodsid the value for shopcar.goodsid
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.count
     *
     * @return the value of shopcar.count
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.count
     *
     * @param count the value for shopcar.count
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.status
     *
     * @return the value of shopcar.status
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.status
     *
     * @param status the value for shopcar.status
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.ordertime
     *
     * @return the value of shopcar.ordertime
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.ordertime
     *
     * @param ordertime the value for shopcar.ordertime
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }
}