spring: 
 datasource:
  url: jdbc:mysql://127.0.0.1:3306/sell?serverTimezone=GMT%2B8
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: a
  
  # 配置静态文件扫描
 resources:
  staticLocations: 
    - file:/Users/longhongjiang/Downloads/myweb/
    - classpath:/static/
    - classpath:/public/
 
 
 
 mvc:
  view:
    prefix: WEB-INF/jsp/
    suffix: .jsp
   
logging:
 level:
   root: ERROR
   com.yc.SellStore: DEBUG
   

   