package com.yc.SellStore.dao;

import com.yc.SellStore.bean.Clientinfo;
import com.yc.SellStore.bean.ClientinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    long countByExample(ClientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    int deleteByExample(ClientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    int deleteByPrimaryKey(Integer clientid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    int insert(Clientinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    int insertSelective(Clientinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    List<Clientinfo> selectByExample(ClientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    Clientinfo selectByPrimaryKey(Integer clientid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") Clientinfo record, @Param("example") ClientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    int updateByExample(@Param("record") Clientinfo record, @Param("example") ClientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    int updateByPrimaryKeySelective(Clientinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientInfo
     *
     * @mbg.generated Tue May 07 19:37:13 CST 2019
     */
    int updateByPrimaryKey(Clientinfo record);
}