package com.yc.SellStore.dao;

import com.yc.SellStore.bean.Collect;
import com.yc.SellStore.bean.CollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    long countByExample(CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    int deleteByExample(CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    int insert(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    int insertSelective(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    List<Collect> selectByExample(CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    Collect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Collect record, @Param("example") CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    int updateByExample(@Param("record") Collect record, @Param("example") CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    int updateByPrimaryKeySelective(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Tue May 14 21:47:48 CST 2019
     */
    int updateByPrimaryKey(Collect record);
}