
package com.yc.SellStore.dao;

import com.yc.SellStore.bean.Evalute;
import com.yc.SellStore.bean.EvaluteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EvaluteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evalute
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    long countByExample(EvaluteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evalute
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    int deleteByExample(EvaluteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evalute
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    int insert(Evalute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evalute
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    int insertSelective(Evalute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evalute
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    List<Evalute> selectByExample(EvaluteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evalute
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") Evalute record, @Param("example") EvaluteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evalute
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    int updateByExample(@Param("record") Evalute record, @Param("example") EvaluteExample example);
    
    int updateByPrimaryKeySelective(Evalute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    int updateByPrimaryKey(Evalute record);
}