
package com.yc.SellStore.dao;

import com.yc.SellStore.bean.Olderlist;
import com.yc.SellStore.bean.OlderlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OlderlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderlist
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    long countByExample(OlderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderlist
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    int deleteByExample(OlderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderlist
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    int insert(Olderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderlist
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    int insertSelective(Olderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderlist
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    List<Olderlist> selectByExample(OlderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderlist
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") Olderlist record, @Param("example") OlderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderlist
     *
     * @mbg.generated Wed May 08 21:34:33 CST 2019
     */
    int updateByExample(@Param("record") Olderlist record, @Param("example") OlderlistExample example);
    
    int updateByPrimaryKeySelective(Olderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbg.generated Wed May 08 20:04:42 CST 2019
     */
    int updateByPrimaryKey(Olderlist record);
}