package com.yc.SellStore.dao;

import com.yc.SellStore.bean.Olderlist;
import com.yc.SellStore.bean.OlderlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OlderlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    long countByExample(OlderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    int deleteByExample(OlderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    int insert(Olderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    int insertSelective(Olderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    List<Olderlist> selectByExample(OlderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    Olderlist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") Olderlist record, @Param("example") OlderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    int updateByExample(@Param("record") Olderlist record, @Param("example") OlderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    int updateByPrimaryKeySelective(Olderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table olderList
     *
     * @mbg.generated Sat Apr 27 19:50:22 CST 2019
     */
    int updateByPrimaryKey(Olderlist record);
}