package com.yc.SellStore.dao;

import com.yc.SellStore.bean.Orderlist;
import com.yc.SellStore.bean.OrderlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    long countByExample(OrderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    int deleteByExample(OrderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    int insert(Orderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    int insertSelective(Orderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    List<Orderlist> selectByExample(OrderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    Orderlist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") Orderlist record, @Param("example") OrderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    int updateByExample(@Param("record") Orderlist record, @Param("example") OrderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    int updateByPrimaryKeySelective(Orderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderList
     *
     * @mbg.generated Mon May 20 20:44:52 CST 2019
     */
    int updateByPrimaryKey(Orderlist record);
}